global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: reports
  tag: latest

service:
  type: ClusterIP
  port: 8051

config:
  OPENMRS_DB_NAME: "openmrs"
  OPENMRS_HOST: "openmrs"
  OPENMRS_PORT: "8080"
  REPORTS_DB_NAME: "bahmni_reports"

secrets:
  OPENMRS_DB_HOST: ""
  OPENMRS_DB_USERNAME: ""
  OPENMRS_DB_PASSWORD: ""
  REPORTS_DB_SERVER: ""
  REPORTS_DB_USERNAME: ""
  REPORTS_DB_PASSWORD: ""
  OPENELIS_DB_SERVER: ""
  ODOO_DB_SERVER: ""
  ODOO_DB_USERNAME: ""
  ODOO_DB_PASSWORD: ""

autoscaling:
  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 5
  #  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
affinity: {}
tolerations: {}
