apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OPENMRS_DB_NAME: "{{ .Values.config.OPENMRS_DB_NAME }}"
  OPENMRS_HOST: "{{ .Values.config.OPENMRS_HOST }}"
  OPENMRS_PORT: "{{ .Values.config.OPENMRS_PORT }}"
  REPORTS_DB_NAME: "{{ .Values.config.REPORTS_DB_NAME }}"
